# install OS package
# install AUR
# configure user dotfiles
# install apps from pacman and AUR

- name: Install OS Packages
  hosts: desktop
  tags: os
  tasks:
    - import_role:
        name: common.os

- name: Install AUR Packages
  hosts: desktop
  tags: aur
  tasks:
    - import_role:
        name: common.aur
