# install OS package
# install AUR
# configure user dotfiles
# install apps from pacman and AUR

- name: Install OS Packages
  hosts: desktop
  tags: os
  tasks:
    - import_role:
        name: common.os

- name: Install AUR Packages
  hosts: desktop
  tags: aur
  tasks:
    - import_role:
        name: common.aur

- name: Install Snap Packages
  hosts: desktop
  tags: snap
  tasks:
    - import_role:
        name: common.snap

- name: Install AppImage Applications
  hosts: desktop
  tags: appimage
  tasks:
    - import_role:
        name: common.appimage
