---
- name: Enable docker
  systemd:
    state: started
    name: docker
    enabled: true
  become: true

# set sudoless docker
# create docker group
# add our user to docker group
- name: Create Docker Group
  group:
    name: docker
    state: present

- name: Get User
  set_fact:
    home_user: "{{ lookup('env', 'USER') }}"

- debug:
    msg: "the user is {{ home_user }}"
  become: true

# - name: Add User to Docker Group
#   user:
#     name: "{{ home_user }}"
#     groups: "docker"
#     append: true
#   become: true