---
- name: Enable docker
  systemd:
    state: started
    name: docker
    enabled: true
  become: true

- name: Create Docker Group
  group:
    name: docker
    state: present

- name: Get User
  set_fact:
    home_user: "{{ lookup('env', 'USER') }}"

- name: Add User to Docker Group
  user:
    name: "{{ home_user }}"
    groups: "docker"
    append: true
  become: true

- debug:
    msg: "Will need to logout and back in to apply change"