---
# check if gotify-desktop is installed
- name: Check for gotify-desktop
  shell: "pacman -Q gotify-desktop"
  become: no
  failed_when: "gotify_desktop_check == 2"
  register: gotify_desktop_check
  changed_when: false

# copy configuration toml
- name: Copy gotify desktop configuration
  template:
    src: "../templates/gotify_desktop_config.toml.j2"
    dest: "/home/{{ username }}/.config/gotify-desktop/config.toml"
    owner: "{{ username }}"
    group: "{{ username }}"
  when: gotify_desktop_check != 2
