---
- name: Get User
  set_fact:
    home_user: "{{ lookup('env', 'USER') }}"

# Install Dotfiles
- include_tasks: dotfiles.yaml
  tags: dotfiles
  vars:
    username: "{{ home_user }}"
  when: user.dotfiles_install|bool

# Configure Docker
- name: Check for Virtualization Enabled
  set_fact:
    virt_enabled: true
  when: ansible_facts.virtualization_type is defined

- include_tasks: docker.yaml
  when: virt_enabled == true

- include_tasks: gotify.yaml
  vars:
    username: "{{ home_user }}"
  when: gotify.enabled|bool

- include_tasks: openvpn.yaml
  when: openvpn.enabled|bool
