# core apps
pacman_core_apps:
  - git
  - tree
  - dosfstools
  - htop
  - zsh
  - vim
  - tmux
  - veracrypt
  - obsidian
  - nextcloud-client
  - keybase

# Terminal Emulators
terminal_apps:
  - alacritty

# File Manager
filemanager_apps:
  - dolphin

# OS Specific
hardware_package:
  - amd-ucode

# Web Browsers
web_browsers_apps:
  - firefox

# communications
communication_apps:
  - discord

# 3d apps
graphical_apps:
  - blender
  - steam

nvidia_apps:
  - nvidia
  - nvidia-settings
  - nvtop

# virtualization
virt_apps:
  - docker
  - docker-compose
  - virt-manager

# dev ops tools
dev_apps:
  - terraform
  - github-cli

# Audio and Video
media_apps:
  - vlc
  - mpv

# Audio and Video editing
av_edit_apps:
  - handbrake
  - mkvtoolnix-cli
  - mkvtoolnix-gui
  - audacity

# graphics
graphic_apps:
  - gimp
  - okula
  - krita

# streaming/production
stream_apps:
  - obs-studio
  
graphics_card_enabled: false
virt_enabled: false
av_enabled: "{% if laptop == true %}true{% else %}false{% endif %}"
streaming_enabled: "{% if laptop == true %}true{% else %}false{% endif %}"
nvidia_enabled: "{% if nvidia_check != 2 %}true{% else %}false{% endif %}"