# core apps
pacman_core_apps:
  - git
  - tree
  - dosfstools
  - htop
  - zsh
  - vim
  - tmux
  - veracrypt
  - obsidian
  - nextcloud-client
  - fzf
  - stow
  - zip
  - unzip
  - unrar
  - nfs-utils
  - gnu-netcat
  - cronie
  - zoxide
  - dfu-programmer
  - git-lfs

audio_apps:
  - pulseaudio
  - pulseaudio-alsa
  - pulseaudio-bluetooth

# Terminal Emulators
terminal_apps:
  - alacritty
  - xterm

# x11
x11_apps:
  - xclip
  - xsel

# wayland
wayland_apps:
  - wl-clipboard

# OS Specific
hardware_package:
  - amd-ucode

# Web Browsers
web_browsers_apps:
  - firefox

# communications
communication_apps:
  - discord

# 3d apps
graphical_apps:
  - blender
  - steam

nvidia_apps:
  - nvidia
  - nvidia-settings
  - nvtop

# virtualization
virt_apps:
  - docker
  - docker-compose
  - virt-manager
  - qemu-desktop
  - bridge-utils
  - libguestfs
  - dnsmasq
  - swtpm
  - freerdp
  - dmidecode

# dev ops tools
dev_apps:
  - terraform
  - github-cli
  - kubectl
  - npm

# Audio and Video
media_apps:
  - vlc
  - mpv

# Audio and Video editing
av_edit_apps:
  - handbrake
  - mkvtoolnix-cli
  - mkvtoolnix-gui
  - audacity
  - libdvdcss

# graphics
graphic_apps:
  - gimp
  - okular
  - krita
  - darktable

# streaming/production
#stream_apps:
#  - obs-studio

# fonts
fonts_install:
  - otf-ipafont
  - ttf-baekmuk
  - noto-fonts-emoji

graphics_card_enabled: false
virt_enabled: false
av_enabled: "{% if laptop|bool == true %}true{% else %}false{% endif %}"
streaming_enabled: "{% if laptop|bool == true %}true{% else %}false{% endif %}"
nvidia_enabled: "{% if nvidia_check != 2 %}true{% else %}false{% endif %}"

pacman_config: "/etc/pacman.conf"
makepkg_config: "/etc/makepkg.conf"
