---
- name: Installing AppImageLauncher from AUR
  kewlfft.aur.aur:
    name: "appimagelauncher"
    state: present
    use: yay

- name: Check for OpenGL
  shell: "glxinfo | grep OpenGL"
  become: no
  failed_when: "opengl_check == 2"
  register: opengl_check
  changed_when: false

- name: Download and Install LycheeSlicer v{{ lycheeslicer_version }}
  get_url:
    url: "{{ lycheeslicer_download }}"
    dest: "{{ appimage_dir }}"
    mode: 0755
  when:
    - opengl_check != 2
    - appimage.slicer_install|bool
