---
- name: Check for Nvidia Card
  shell: 'lspci -k | grep -A 2 -E "(VGA|3D)"'
  become: no
  failed_when: "nvidia_check == 2"
  register: nvidia_check
  changed_when: false

- name: Install Core Apps
  kewlfft.aur.aur:
    name: "{{ item }}"
    state: present
    use: yay
  loop: "{{ aur_core_packages }}"

- name: Install Fonts
  kewlfft.aur.aur:
    name: "{{ item }}"
    state: present
    use: yay
  loop: "{{ fonts_package }}"

- name: Install Browser Apps
  kewlfft.aur.aur:
    name: "{{ item }}"
    state: present
    use: yay
  loop: "{{ browser_packages }}"
  when: aur.browser_install|bool

- name: Install Ledger App
  kewlfft.aur.aur:
    name: "{{ ledger_package }}"
    state: present
    use: yay
  when: aur.ledger_install|bool

- name: Install Dropbox App
  kewlfft.aur.aur:
    name: "{{ dropbox_package }}"
    state: present
    use: yay
  when: aur.dropbox_install|bool

- name: Install Audio/Video Editing Apps
  kewlfft.aur.aur:
    name: "{{ item }}"
    state: present
    use: yay
  loop: "{{ av_edit_apps }}"
  when:
    - aur.av_install|bool
    - not laptop|bool

- name: Install Graphics Apps
  kewlfft.aur.aur:
    name: "{{ item }}"
    state: present
    use: yay
  loop: "{{ image_apps }}"
  when: aur.image_pkg_install|bool

- name: Install 3D Printing Apps
  kewlfft.aur.aur:
    name: "{{ item }}"
    state: present
    use: yay
  loop: "{{ slicer_apps }}"
  when:
    - aur.slicer_install|bool
    - graphics_card_enabled|bool

- name: Install Dev Tools
  kewlfft.aur.aur:
    name: "{{ item }}"
    state: present
    use: yay
  loop: "{{ dev_apps }}"
  when: aur.dev_install|bool
