---
- name: Check if Yay is installed
  shell: "yay --version"
  become: no
  failed_when: "yay_check == 2"
  register: yay_check
  changed_when: false

- debug:
    msg: "{{ yay_check.stdout }}"

- name: Git Clone Yay
  git:
    dest: "/tmp/yay"
    repo: "{{ yay_repo }}"
  when: "yay_check != 0"

- name: Install Yay
  shell: "cd /tmp/yay && makepkg -si --noconfirm"
  become: no
  failed_when: "yay_make == 2"
  register: yay_make
  when: "yay_check != 0"

- debug:
    msg: "{{ yay_make.stdout }}"
  when: "yay_check != 0"

- include_tasks: apps.yaml
  when: yay_check != 2