---
- name: Check for Nvidia Card
  shell: "lspci -k | grep -A 2 -E \"(VGA|3D)\""
  become: no
  failed_when: "nvidia_check == 2"
  register: nvidia_check
  changed_when: false

- name: Set Base Apps to Install
  set_fact:
    snap_combined_apps: "{{ snap_core_packages }}"

- name: Install Apps (Snap)
  community.general.snap:
    name: "{{ item }}"
    state: present
  loop: "{{ snap_combined_apps }}"
  become: true

- name: Install Fusion360 App (Snap)
  community.general.snap:
    name: "fusion360"
    state: present
    channel: beta
    classic: true
  become: true
  when: nvidia_check != 2 and nvidia_check.stdout >= 1