---
- name: Check if Snap is installed
  shell: "snap version"
  become: no
  failed_when: "snap_check == 2"
  register: snap_check
  changed_when: false

- debug:
    msg: "{{ snap_check.stdout }}"

- name: Installing snapd from AUR
  kewlfft.aur.aur:
    name: "snapd"
    state: present
    use: yay
  when: snap_check != 2

- name: Enable AppArmor
  systemd:
    state: started
    enabled: true
    name: apparmor

- name: Enable Snapd AppArmor
  systemd:
    state: started
    enabled: true
    name: snapd.apparmor

- name: Enable Snapd
  systemd:
    state: started
    enabled: true
    name: snapd

- include_tasks: apps.yaml
  when: snap_check != 2