---
- name: Install Display Manager (SDDM)
  pacman:
    name: "{{ sddm_package }}"
    state: present
  become: true

- name: Install SDDM KDE Integration
  pacman:
    name: "sddm-kcm"
    state: present
  become: true
  when: display_manager.type == "plasma"

- name: Enable SDDM
  systemd:
    name: "{{ sddm_package }}"
    enabled: true
  when: not chrooted|bool

# Install custom theme(s)
- name: Download Sugar Candy SDDM theme
  get_url:
    url: "{{ sugar_candy_download }}"
    dest: "/tmp/sugar-candy.tar.gz"

# unarchive
- name: Extract Sugar Candy SDDM Theme
  unarchive:
    src: "/tmp/sugar-candy.tar.gz"
    dest: "{{ sddm_themes_dir }}"
    owner: "root"
    group: "root"
  become: yes

# copy over theme configuration and files
- name: Download Wallpaper
  get_url:
    url: "{{ theme_image_url }}"
    dest: "{{ sugar_candy_theme_dir }}/sddm_wallpaper.png"
    group: "root"
    owner: "root"
  become: true

- name: Set Screen Width
  shell: 'xdpyinfo | grep "dimensions" | sed -E "s/.* ([0-9]+)x[0-9]+ pixels.*/\1/"'
  become: no
  failed_when: "screen_width == 2"
  register: screen_width
  changed_when: false

- name: Set Screen Height
  shell: 'xdpyinfo | grep "dimensions" | sed -E "s/.* [0-9]+x([0-9]+) pixels.*/\1/"'
  become: no
  failed_when: "screen_height == 2"
  register: screen_height
  changed_when: false

- name: Configuring Theme
  template:
    src: "../templates/sugar_candy_theme.conf.j2"
    dest: "{{ sugar_candy_theme_dir }}/theme.conf"
    owner: "root"
    group: "root"
  become: true

# install theme dependencies
- name: Install theme dependencies
  pacman:
    name: "{{ item }}"
    state: present
  become: true
  loop: "{{ theme_depen_packages }}"

- name: Set Sugar Candy as default SDDM
  template:
    src: "../templates/sddm.conf.j2"
    dest: "{{ sddm_conf }}"
    owner: "root"
    group: "root"
  become: true
