- name: Pacman Updates
  pacman:
    update_cache: yes
    upgrade: yes
  become: true

- name: Install Core Apps
  pacman:
    name: "{{ item }}"
    state: present
  loop: "{{ pacman_core_apps }}"
  become: true