---
- name: Check for Nvidia Card
  shell: "lspci -k | grep -A 2 -E \"(VGA|3D)\""
  become: no
  failed_when: "nvidia_check == 2"
  register: nvidia_check
  changed_when: false

- name: Pacman Updates
  pacman:
    update_cache: yes
    upgrade: yes
  become: true

- name: Set Base Apps to Install
  set_fact:
    pacman_combined_apps: "{{ pacman_core_apps + terminal_apps + filemanager_apps + web_browsers_apps + media_apps  + graphic_apps + communication_apps + dev_apps }}"

- name: Add Nvidia Packages
  set_fact:
    pacman_combined_apps: "{{ pacman_combined_apps + nvidia_apps }}"
  when: "nvidia_enabled == true"

- name: Combine with Graphics Card Apps
  set_fact:
    pacman_combined_apps: "{{ pacman_combined_apps + graphical_apps }}"
  when: "graphics_card_enabled == true"

- name: Combine with Virtualized Development Apps
  set_fact:
    pacman_combined_apps: "{{ pacman_combined_apps + virt_apps }}"
  when: "virt_enabled == true"

- name: Combine with Audio/Video Editing Apps
  set_fact:
    pacman_combined_apps: "{{ pacman_combined_apps + av_edit_apps }}"
  when: "av_enabled == true"

- name: Combine with Streaming/Production Apps
  set_fact:
    pacman_combined_apps: "{{ pacman_combined_apps + stream_apps }}"
  when: "streaming_enabled == true"

- name: Install Apps (Pacman)
  pacman:
    name: "{{ item }}"
    state: present
  loop: "{{ pacman_combined_apps }}"