dotfiles_packages:
  - nvim
  - zsh
  - stow
  - git
  - fzf
  - zoxide
  - ripgrep
  - npm

dotfiles_packages_x11:
  - xsel
  - xclip

dotfiles_packages_wayland:
  - wl-clipboard

git_clone_method: "{{ user.git_clone_method | default('https') }}"
dotfiles_repo: "{% if git_clone_method == 'ssh' %}git@github.com:{% else %}https://github.com/{% endif %}sinicide/.dotfiles.git"
oh_my_zsh_url: "https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh"
docker:
  enabled: "{{ user.docker.enabled | default(false) }}"

openvpn:
  enabled: "{{ user.openvpn.enabled | default(false) }}"

openvpn_packages:
  - openvpn
  - networkmanager-openvpn

# Gotify Desktop Configuration
gotify:
  enabled: "{{ user.gotify.enabled | default(false) }}"
  url: "wss://{{ user.gotify.endpoint }}"
  user_token: "{{ user.gotify.user_token }}"
